spring:
  application:
    name: User-service

#  profiles:
#    active: maintenance

  mvc:
    throw-exception-if-no-handler-found: true


  web:
    resources:
      add-mappings: false



  data:
    mongodb:
      uri: mongodb://localhost:27017/agrolink


jwt:
  secretJwtString: AgroLinkSecretKeyDevlopersSourav&Souvik





