server:
    port: 8088

spring:
    application:
        name: admin-service

    data:
        mongodb:
            uri: mongodb://localhost:27017/admin-service-db

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
