server:
    port: 8086

spring:
    application:
        name: advisory-service

    config:
        import: configserver:http://localhost:8090
    profiles:
        active: prod

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always
