server:
    port: 8086

spring:
    application:
        name: advisory-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/agrolink_advisory
    config:
        import: configserver:http://localhost:8090
    profiles:
        active:

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always
