server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/agrolink

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
