server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/agrolink

  config:
    import: configserver:http://localhost:8090
  profiles:
    active:
