server:
  port: 8089

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG # Add this line for Spring Security logging
    com.AgroLink.User.security.filter: DEBUG # Add this line for your custom filters


spring:
  application:
    name: gateway

  config:
    import: configserver:http://localhost:8090
  profiles:
    active:

  cloud:
    discovery:
      enabled: true

    gateway:
      server:
        webflux:
          # Removed the empty filter entry to fix the startup error.
          default-filters: []
          routes:
            - id: user-service-auth
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/auth/**
              filters:
                - StripPrefix=1
                - RewritePath=/(?<segment>.*), /api/${segment}

            - id: user-service-users
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**
              filters:
                - RewritePath=/user(?<segment>.*), /api/users${segment}

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**
              filters:
                - RewritePath=/notifications/(?<segment>.*), /api/notifications/${segment}

            - id: advisory-service-advisory
              uri: lb://advisory-service
              predicates:
                - Path=/advisory/**
              filters:
                - RewritePath=/advisory(?<segment>.*), /api/advisory${segment}

            - id: advisory-service-query
              uri: lb://advisory-service
              predicates:
                - Path=/query/**
              filters:
                - RewritePath=/query(?<segment>.*), /api/query${segment}

            - id: admin-service
              uri: lb://admin-service
              predicates:
                - Path=/admin/**
              filters:
                - RewritePath=/admin(?<segment>.*), /api/admin${segment}

            - id: warehouse-service
              uri: lb://warehouse-service
              predicates:
                - Path=/warehouse/**
              filters:
                - RewritePath=/warehouse(?<segment>.*), /api/warehouse${segment}
