# Server Port
server:
  port: 8087

# Application Name
spring:
  application:
    name: notification-service
  config:
    import: configserver:http://localhost:8090
  profiles:
    active: prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: souvik@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true