# ──────────────────────────────────────────────────────────────
# 🔧 Maintenance Mode Configuration Manual
# ──────────────────────────────────────────────────────────────
# This configuration file is used to temporarily restrict access
# to specific URL paths and/or requests from specific Origins.
#
# ✅ HOW TO USE:
# 1. Activate this config by:
#    - setting `spring.profiles.active=maintenance`
#      OR
#    - importing this file manually in application.yml
#
# 2. Toggle maintenanceMode to true/false
#    - true = restrict matching paths
#    - false = allow all paths
#
# 3. Update `maintenancePaths` with comma-separated URL prefixes
#    - These paths will return HTTP 503 (Service Unavailable)
#
# 4. (Optional) Restrict requests by Origin header
#    - Set `originRestrictionEnabled` to true
#    - Set `restrictedOrigin` to the origin you want to block
#
# ✅ EXAMPLE BEHAVIOR:
# If a request URI starts with `/api/orders` OR
# the Origin header matches `http://localhost:5173`,
# and the respective toggle is true,
# the request is blocked with 503 response.

# ──────────────────────────────────────────────────────────────
# 📦 Maintenance Configuration Starts Below
# ──────────────────────────────────────────────────────────────

app:
  maintenanceMode: true                        # Full application lock (503 for ALL)
  maintenancePaths: #/api/orders,/api/admin     # Specific paths to block
  originRestrictionEnabled: true               # Enable origin blocking
  restrictedOrigin: http://localhost:5173      # Origin to block
