# User-service application.yml
spring:
  application:
    name: USER-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/agrolink

server:
  port: 8081

jwt:
  secretJwtString: AgroLinkSecretKeyDevlopersSourav&Souvik

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
