# User-service application.yml
spring:
  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8090
  profiles:
    active: prod


server:
  port: 8081

jwt:
  secretJwtString: AgroLinkSecretKeyDevlopersSourav&Souvik


