server:
  port: 8091

spring:
  application:
    name: cart-service
  config:
    import: configserver:http://localhost:8090
  profiles:
    active: prod

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, ratelimiters # <-- Make sure 'ratelimiters' is included

resilience4j:
  circuitbreaker:
    instances:
      productServiceCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  ratelimiter:
    instances:
      productServiceRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 5s
        timeoutDuration: 1s
