server:
  port: 8091

spring:
  application:
    name: cart-service
  config:
    import: configserver:http://localhost:8090
  profiles:
    active: prod

management:
  health:
    circuitbreakers:
      enabled: true



resilience4j:
  circuitbreaker:
    instances:
      productServiceCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  ratelimiter:
    instances:
      productServiceRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 4s
        timeoutDuration: 2s
