server:
  port: 8091

spring:
  application:
    name: cart-service
  config:
    import: configserver:http://localhost:8090
  profiles:
    active:
  data:
    mongodb:
      uri: mongodb://localhost:27017/agrolink

management:
  endpoint:
    web:
        exposure:
            include: health