server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/agrolink
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: configserver:http://localhost:8090
  profiles:
    active:

razorpay:
    key: rzp_test_3VRdkx9nitx82t
    secret: Faq05kXhAkMJTI45Eo2gOJf0


