server:
    port: 8085

spring:
    application:
        name: warehouse-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/agrolink_warehouse

    config:
        import: configserver:http://localhost:8090
    profiles:
        active:

